### PR TITLE
Reconnection backoff delay for workers and schedulers

### LINKED ISSUE #91: Workers and schedulers need a reconnection backoff delay
### Problem
I created multiple jobs (some of which are scheduled) and ran into an issue with underway in cases where the database "disappears", e.g. when deleting and recreating the database during development or simply when the connection drops.

If this happens, underway immediately enters a loop trying to reconnect without any delay between attempts, causing incredible log spam.

### Steps to Reproduce
Simply set up a job and call job.start() to run a worker and scheduler. While the program is running, disallow and kill connections to the database:

```sql
ALTER DATABASE my_db WITH ALLOW_CONNECTIONS FALSE;
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'my_db';
```

underway will immediately enter the reconnection limbo and start spamming errors.

### Solution

I have implemented a quick and dirty fix to work around this issue, see here: https://github.com/maxcountryman/underway/commit/008140f6125ad1e2155128c1fa820ee953d8b893

Of course this would have to be implemented properly in underway, maybe with exponential backoff?

### PR DESCRIPTION
**Pull request by Marvel-Gu**
## Summary

- Extend `task::RetryPolicy` with a configurable jitter factor and use it for reconnection backoff.
- Apply the same jittered exponential reconnection backoff policy to both workers and schedulers.

Fixes   #91

## RetryPolicy & backoff behavior

RetryPolicy is extended with a jitter_factor field and a jitter_factor(...) builder method, and calculate_delay(retry_count) now computes an exponential delay based on initial_interval_ms, max_interval_ms, and backoff_coefficient, then applies jitter by sampling between target * (1.0 - jitter_factor) and target; with the default values (initial_interval_ms = 1_000, max_interval_ms = 60_000, backoff_coefficient = 2.0, jitter_factor = 0.5), retries back off exponentially while being de‑synchronized across processes.

## Worker & scheduler reconnection

Their main loops are wrapped in a shared reconnection pattern: both components maintain a retry_count for connection attempts and, on failure to acquire a pool connection, create a PgListener, or LISTEN on the relevant channel, they compute the next delay via reconnection_policy.calculate_delay(retry_count), log the error with backoff_secs and attempt, sleep for the computed duration, increment retry_count, and retry; on successful connection and subscription they reset retry_count to 1 and then preserve the existing behavior, with workers continuing to process tasks and handle graceful shutdown, and schedulers continuing to enforce the single‑instance advisory lock and iterate the configured schedule.

### CODE REVIEW

File: src/scheduler.rs [hunk 1]
```diff
@@ -51,6 +52,9 @@ pub struct Scheduler<T: Task> {
 
     // When this token is cancelled the queue has been shutdown.
     shutdown_token: CancellationToken,
+
+    // Policy for reconnection backoff when PostgreSQL connection is lost.
+    reconnection_policy: RetryPolicy,
```
Comment (maxcountryman) [inline src/scheduler.rs]: This is a nit but I think it's a bit confusing that we have `RetryPolicy`, connection policy, and task policy. Perhaps there's an opportunity for better naming, if `RetryPolicy` really is applicable to both otherwise distinct types might make better sense.

Comment (maxcountryman) [reply src/scheduler.rs]: I think I'd lean towards the second option if that reduces duplication, but I don't have a strong preference.

File: migrations/20241105164503_2.sql [hunk 2]
```diff
@@ -18,12 +18,13 @@ create type underway.task_retry_policy as (
     max_attempts         int,
     initial_interval_ms  int,
     max_interval_ms      int,
-    backoff_coefficient  float
+    backoff_coefficient  float,
+    jitter_factor        float
```
Comment (maxcountryman) [inline migrations/20241105164503_2.sql]: Sorry for the delay on this. I think we probably want to incorporate these changes in a separate migration, right? 

If we don't, then anyone using Underway today wouldn't have a clean upgrade path. (Maybe that's reasonable for breaking releases, but it would be nice if we could avoid that.)
